load("@envoy//api/bazel:api_build_system.bzl", "api_proto_library")

api_proto_library(
    name = "amqp_client",
    srcs = ["amqp_client.proto"],
)

api_proto_library(
    name = "amqp_server",
    srcs = ["amqp_server.proto"],
)
